ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('ProyectoWebApp.urls')),  
    path('contacto/', include('contacto.urls')),  
    path('tienda/', include('tienda.urls')),  
    path('carro/', include('carro.urls')),  
    path('pedidos/', include('pedidos.urls')),  
    path('autenticacion/', include('autenticacion.urls')),  

]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"


urlpatterns = [    
    
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("sumar/<int:producto_id>/", views.sumar, name="sumar"),

    path("limpiar", views.limpiar_carro, name="limpiar"),
    
]

tienda/urls.py
from django.urls import path
from . import views




urlpatterns = [    
    
    path('', views.Tienda, name='tienda'),
    path('carro/', views.Carro, name='carro'),

    
]

tienda/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoria"
        verbose_name_plural="categorias"
    
    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre=models.CharField(max_length=30)
    categorias=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='tienda')
    precio=models.FloatField()
    stock = models.IntegerField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="producto"
        verbose_name_plural="productos"
                            

tienda/views.py
from django.shortcuts import render
from .models import Producto
# Create your views here.
def Tienda(request):

    productos = Producto.objects.all()
    # modificado
    if request.method == 'POST':
        dato = request.POST.get('prod')
        productos = Producto.objects.filter(nombre__icontains=dato)
    # modificado
        return render(request, 'tienda/tienda.html', {"productos":productos, "query":dato})
    # modificado
    else:
        return render(request, 'tienda/tienda.html', {"productos":productos})


def Carro(request):
    return render(request, 'tienda/widget.html')

tienda/templates/tienda/tienda.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

<style>
  .card:hover {
    /* Agrega aquí los estilos que deseas aplicar cuando se hace hover */
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    transform: translateY(-5px);
  }
</style>





{% if productos %}
<div class="container">

  <div style="float: right;">


  </div>

  <div class="row">

    {% for producto in productos %}
    <div class="col-md-3">
      <div class="card" style="margin: 10px 8px;">

        <img src="{{producto.imagen.url}} " class="card-img-top">
        <div class="card-body" style="text-align: center;">
          <h6 class="card-title">{{producto.nombre}}</h6>
          <p class="card-text"> &nbsp;S/.{{producto.precio}}</p>
        </div>
        <div class="card-footer text-center">
          <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carrito</a>
        </div>
      </div>
    </div>
    {% endfor %}
  {% else %}
   <h1 class="alert alert-danger text-center">No se encontro el producto</h1>
  </div>
</div>
{% endif %}
<!-- <div class="container">

    <div style="float: right;">
        
       
    </div>

    <div class="row">
  
      {% for producto in productos %}
      <div class="col-md-3">
        <div class="card" style="margin: 10px 8px;">
  
          <img src="{{producto.imagen.url}} " class="card-img-top">
          <div class="card-body" style="text-align: center;">
            <h6 class="card-title">{{producto.nombre}}</h6>
            <p class="card-text"> &nbsp;S/.{{producto.precio}}</p>
          </div>
          <div class="card-footer text-center">
                <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carrito</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div> -->


{% endblock %}

tienda/templates/tienda/widget.html
{% extends 'ProyectoWebApp/base.html' %}

{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
<style>
    th,
    td {
        color: black !important;
    }
</style>
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="4" class="text-center">Carro compras</th>
        </tr>
        <tr>
            <th>Nombre Producto</th>
            <th>Cantidad</th>
            <th>Acción</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
        {% for key, value in request.session.carro.items %}
        <tr class="text-center">
            <td>{{value.nombre}}</td>
            <td>{{value.cantidad}}</td>
            <td>

                <a href="{% url 'carro:sumar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br>
                {{value.precio}}

            </td>
            <td><a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-danger">Eliminar</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">
                <div class="alert alert-danger text-center">
                    Sin productos
                </div>
            </td>
        </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">
                <p style="color: black;">Total: {{importe_total_carro}}</p>
            </td>
            {% if request.session.carro.items %}
            <tr>
                <td colspan="4" style="text-align: center;">
                    <a href="{% url 'procesar_pedido'%}" class="btn btn-success">Hacer pedido</a>
                </td>
            </tr>
            {% endif %}
        </tr>
    </tfoot>
</table>
{% else %}  
<!-- <div class="alert alert-danger text-center">INICIAR SESION PARA VER CARRITO</div>   -->
    {% url 'logear' as redirect_url %}    
    {% if redirect_url %}
         <script>window.location.href = "{{ redirect_url }}";</script>
    {% endif %}
{% endif %}
{% endblock %}